"""empty message

Revision ID: 67e5d469fe63
Revises: 6b78fb6f4832
Create Date: 2022-06-07 16:20:41.113103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e5d469fe63'
down_revision = '6b78fb6f4832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.add_column('Venue', sa.Column('website_link',
                  sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column(
        'genres', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=False)
    op.drop_column('Artist', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'website_link')
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
